// Generated by CoffeeScript 1.4.0
(function() {
  var Crafty;

  Crafty = window.Crafty;

  Crafty.c("NewSupportable", {
    init: function() {
      return this.bind("EnterFrame", this.checkSupport);
    }
  });

}).call(this);
